server {
    listen 80;
    server_name localhost;

    # Serve React Static Files
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Reverse Proxy API calls strictly back explicitly to the Spring Boot Container natively bridging the Monolith Contexts!
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_addrs;
    }
}
